dist: xenial
sudo: required

language: python
python:
  - 3.6
  - 3.7
node_js: '8'

install:
  - pip install -U tox-travis
  - pip install python-coveralls
  - npm install @commitlint/travis-cli

script:
  - node_modules/.bin/commitlint-travis
  - tox -r

after_success:
  - coveralls

notifications:
  email: false
